# Site settings
title: Mr Costillas
email: mr.costillas@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mrcostillas.com" # the base hostname & protocol for your site

twitter_username: Mr. Costillas Steak House & Bar
github_username: Mr. Costillas Steak House & Bar

# Build settings
markdown: kramdown
